### ISSUE TITLE
newRunForWorld() call fails, asking for a model

### ISSUE THREAD

**Issue by mmrj** [forio/epicenter-js-libs#88]
for example: 
```
worldSer.getCurrentWorldForUser('42836d4b-5b61-4fe4-80eb-3136e956ee5c', 'js-libs-team2')
  .then(function (world) {
        console.log("world.run = ", world.run);
	worldSer.newRunForWorld(world.id)
	.then(function () {
		worldSer.getCurrentRunId().then (function (runid) { console.log("after new run, current run id = ", runid)});
	});
});
```

gives `Uncaught Error: No model specified to get the current run`

**Comment by mmrj** [comment]
@jaimedp says he has a fix for this already

**Comment by jaimedp** [comment]
Fixed by 3691ef4d73ec1647da29b872bb22b26e18ec5c7c

**Comment by mmrj** [comment]
reopening after testing in 1.5.

if i don't pass in the model when creating the WorldManager, i still get `Uncaught Error: No model specified to get the current run` at `worldSer.newRunForWorld()` call:

```
        //logged in as a team member using auth.login

	var wMgr = new F.manager.WorldManager({
			account: 'acme-simulations-0',
			project: 'hello_world_python',
			group: 'js-libs-team2',
			model: 'hello_world.py'
	});

        // this is an end user in this group + project
	wMgr.getCurrentWorld('42836d4b-5b61-4fe4-80eb-3136e956ee5c')
		.then(function(world, worldSer) {
			worldSer.getCurrentWorldForUser('42836d4b-5b61-4fe4-80eb-3136e956ee5c', 'js-libs-team2')
  				.then(function (world) {
        			console.log("world.run = ", world.run);
    				worldSer.newRunForWorld(world.id)
    					.then(function () {
        					worldSer.getCurrentRunId()
        						.then (function (runid) { console.log("after new run, current run id = ", runid)});
    					});
				});
		});

however, if i explicitly pass the model in to that call, it works fine:
```
worldSer.newRunForWorld(world.id, {model: 'hello_world.py'})
```

**Comment by mmrj** [comment]
https://issues.forio.com/browse/EPICENTER-1459
